// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ELEVATE - Transform Your Life, One Day at a Time",
  description: "The only app that unites style, fitness, nutrition, beauty, and organization in one intelligent AI-powered platform. Join 500K+ users transforming their lifestyle.",
  keywords: "lifestyle app, AI fitness, personalized nutrition, style management, skincare routine, habit tracker, wellness app",
  openGraph: {
    title: "ELEVATE - AI-Powered Lifestyle Transformation",
    description: "Transform your life with AI-powered guidance across style, fitness, nutrition, beauty, and organization.",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
